sites:
  SITE_A:
    assets:
      PUMP_01:
        points:
          P1MT:
            rpm: 2980
          P2MT:
            rpm: 2980
          P3GX:
            rpm: 2980
          P4GX:
            rpm: 2980
          P5GX:
            rpm: 2980
          P6GX:
            rpm: 2980
          P7PP:
            rpm: 2980
          P8PP:
            rpm: 2980
      PUMP_02:
        points:
          P1MT:
            rpm: 2980
          P2MT:
            rpm: 2980
          P3GX:
            rpm: 2980
          P4GX:
            rpm: 2980
          P5GX:
            rpm: 2980
          P6GX:
            rpm: 2980
          P7PP:
            rpm: 2980
          P8PP:
            rpm: 2980
  SITE_B:
    assets:
      PUMP_03:
        points:
          P1MT:
            rpm: 2980
          P2MT:
            rpm: 2980
          P3GX:
            rpm: 2980
          P4GX:
            rpm: 2980
          P5GX:
            rpm: 2980
          P6GX:
            rpm: 2980
          P7PP:
            rpm: 2980
          P8PP:
            rpm: 2980