sites:
  SITE_A:
    criticality: high
    assets:
      PUMP_01:
        criticality: high
        points:
          P1MT:
            type: motor
            rpm: 2980
            enabled: true
          P3GX:
            type: gearbox
            rpm: 1480
            enabled: true

  SITE_B:
    criticality: medium
    assets:
      COMP_01:
        criticality: medium
        points:
          P1MT:
            type: motor
            rpm: 2960
            enabled: true
